name: staging

on:
  push:
    branches:
      - staging
      - "revert-*-staging"
      - "**/revert-*-staging"
  repository_dispatch:
    types: trigger_staging_ci

jobs:
  ci_staging:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Display runner status
        run: |
          echo "hostname -f: $(hostname -f)"
          echo "whoami: $(whoami)"

      # - name: Autoupdate PR
      #   uses: docker://chinthakagodawita/autoupdate-action:v1
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #     MERGE_CONFLICT_ACTION: ignore

      - run: sudo chown -R $(whoami):$(whoami) .
      - name: Run git checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          clean: true
          submodules: recursive

      - name: Start snackerloo-sdk container
        run: |
          source ext/.bashrc
          sudo ext/sdkpull
          sudo -E docker-compose -f sdk/ci.yml up -d
          sudo ext/runinsdk -f sdk/ci.yml <<< "
            docker system prune --volumes --force
            wait-swarm
          "

      - name: Run style check
        run: |
          sudo ext/runinsdk -f sdk/ci.yml <<< "
            stylecheck
          "

      - name: Build project in snackerloo-sdk
        run: |
          sudo ext/runinsdk -f sdk/ci.yml <<< "
            deploy --build --rm --config=ci --tag=staging-${GITHUB_SHA::7} ||\
            ( docker system prune --all -f --volumes &&\
              deploy --build --no-cache --rm --config=ci --tag=staging-${GITHUB_SHA::7} )
          "

      - name: Run tests
        run: |
          sudo ext/runinsdk -f sdk/ci.yml <<< "
            dx site -T -- runtest --parallel --verbose --bail --nomock
          "

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: tmp/screenshots
